### ISSUE TITLE
Spark Monotask

### ISSUE THREAD

**Issue by zainryan** [kayousterhout/monotasks-scripts#25]
Hi, Kay! I listened to your talk on Spark Summit 2016 and I'm very interested about that. It seems that you're working on spark-1 repository. Is this the source code of your Spark Monotask project?

**Comment by kayousterhout** [comment]
Glad to hear of your interest! The source code is not currently public (this directory contains scripts we've been using to parse results of experiments, but not the code to actually run those experiments).  We expect to open-source it sometime in the next few months.
